export const REVEAL_CELL = 'REVEAL_CELL';
export const FLAG_CELL = 'FLAG_CELL';
export const REVEAL_ALL_ADJACENT = 'REVEAL_ALL_ADJACENT';
export const FLAG_OR_REVEAL_ALL_ADJACENT = 'FLAG_OR_REVEAL_ALL_ADJACENT';